### ISSUE TITLE
what does the scuttle- prefix mean?

### ISSUE THREAD

**Issue by dominictarr** [ssbc/scuttle-gathering#5]
I remember @ahdinosaur you disliked the catch all `ssb-` prefix... but it seems to me that `scuttle-` is an equally vague collection of everything? is there a well defined scope? When should something have a scuttle- prefix and when should it have ssb- prefix?

There are some things that seem to do the same thing as other things

Are these good and used and should they be added to the village tracker
or should they be shifted to [the junkyard](https://github.com/ssb-junkyard)?

**Comment by ahdinosaur** [comment]
who me? couldn't be! :smiley_cat: 

@mixmix and @pietgeursen [stole the cookies from the cookie jar!](https://en.wikipedia.org/wiki/Who_Stole_the_Cookie_from_the_Cookie_Jar%3F) :cookie: 

---

some archeology :information_source:  

- [`%TZxzMKHBihnrF1KcgjaBoih41N0rUm/CCSOjhlUmhR0=.sha256`](https://viewer.scuttlebot.io/%25TZxzMKHBihnrF1KcgjaBoih41N0rUm%2FCCSOjhlUmhR0%3D.sha256)
-  [`%d5O4ZZoU7S3e2Dq96JOAgLKpfnYDsx0g32SQDey56wM=.sha256`](https://viewer.scuttlebot.io/%25d5O4ZZoU7S3e2Dq96JOAgLKpfnYDsx0g32SQDey56wM%3D.sha256)

> ## Scuttle helpers
>
> higher level functions which do streaming, publishing, and synthesis of messages into objects useful for clients. We put a strong focus on building these to be client agnostic, so [scuttle-poll](https://github.com/ssbc/scuttle-poll) takes a server, a server connection, or an observeable which will resolve to a server connection, and instantiates a helper with all the relevant methods you need.
This has meant we can collect (and then pretty much ignore) all of the logic you might need to run polls, worrying about message types, figuring out how to collect and condense results etc, and just focus on how you'd like to lay that data out.
> Similar to the schemas / validators, we've also seen this pattern be really useful and start to proliferate into other code:
> - [scuttle-blog](https://github.com/ssbc/scuttle-blog)
> - [scuttle-invite](https://github.com/ssbc/scuttle-invite)
> - [scuttle-gathering](https://github.com/ssbc/scuttle-gathering) (this needs work) 
> - [scuttle-tag](https://github.com/ssbc/scuttle-tag)
> - [scuttle-book](https://github.com/arj03/scuttle-book)

**Comment by mixmix** [comment]
well summarised.

The distinction I'd make is that `ssb-modules` seem to be `ssb-server` plugins (mostly), whereas `scuttle-modules` can be used client side, or used inside `ssb-server` plugins.

FWIW I would have prefixed these modules `hermes-modules` if it hadn't been for those delinquents with their damn hermies obsession. Because hermes was the OG helper for adventurers >:(

**Comment by dominictarr** [comment]
> whereas scuttle-modules can be used client side, or used inside ssb-server plugins

Hmm, a quick look I found many `ssb-` modules that also cover a situation like that.

`ssb-ref, ssb-keys, ssb-markdown, ssb-mentions, ssb-validate, ssb-caps, ssb-threads, ssb-schema-definitions, ssb-blob-files, ssb-poll-schema`

hmm, also `ssb-server` isn't an sbot plugin anymore... it's a special case now

Another pattern is it seems that all the `scuttle-` modules use the `art.hack.` naming style
